dist: trusty

language: java

jdk:
  - oraclejdk8

script:
    - cp excel2csv build/libs/
    - bash build/libs/excel2csv -h || true
    - bash build/libs/excel2csv test_data/simple01.xlsx
    - ./gradlew test jacocoTestReport;

after_success:
    - bash <(curl -s https://codecov.io/bash)
