dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

script:
    - cat excelToCsv.stub build/libs/excelToCsv.jar > excelToCsv && chmod a+x excelToCsv
    - cp excelToCsv build/libs/
    - ./excelToCsv -h || true
    - ./excelToCsv test_data/simple01.xlsx
    - ./gradlew test jacocoTestReport;

after_success:
    - bash <(curl -s https://codecov.io/bash)
