name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        run: |
          ./gradlew build
          cat excelToCsv.stub build/libs/excelToCsv.jar > excelToCsv && chmod a+x excelToCsv
          cp excelToCsv build/libs/
          ./excelToCsv -h || true
          ./excelToCsv -i test_data/simple01.xlsx
          ./gradlew test jacocoTestReport;
          bash <(curl -s https://codecov.io/bash)
